export const CategoriasReceitas = {
  BOLOS_E_TORTAS: "BOLOS_E_TORTAS",
  CARNES: "CARNES",
  AVES: "AVES",
  PEIXES_E_FRUTOS_DO_MAR: "PEIXES_E_FRUTOS_DO_MAR",
  SALADAS_E_MOLHOS: "SALADAS_E_MOLHOS",
  SOPAS: "SOPAS",
  MASSAS: "MASSAS",
  BEBIDAS: "BEBIDAS",
  DOCES_E_SOBREMESAS: "DOCES_E_SOBREMESAS",
  LANCHES: "LANCHES",
  ALIMENTACAO_SAUDAVEL: "ALIMENTACAO_SAUDAVEL",
};
