export const CategoriasReceitas = {
  ALIMENTACAO_SAUDAVEL: "ALIMENTACAO_SAUDAVEL",
  AVES: "AVES",
  BEBIDAS: "BEBIDAS",
  BOLOS_E_TORTAS: "BOLOS_E_TORTAS",
  CARNES: "CARNES",
  DOCES_E_SOBREMESAS: "DOCES_E_SOBREMESAS",
  LANCHES: "LANCHES",
  MASSAS: "MASSAS",
  PEIXES_E_FRUTOS_DO_MAR: "PEIXES_E_FRUTOS_DO_MAR",
  // SALADAS_E_MOLHOS: "SALADAS_E_MOLHOS",
  // SOPAS: "SOPAS",
};
